favicon: assets/favicon.ico
logo: assets/logo.png

# navbar
github_url: https://github.com/StrixSC/
mastodon_url: https://mastodon.social/explore
linkedin_url: https://linkedin.com
twitter_url: https://twitter.com/S7RIX

accent_color: B0D9FF


# Archive:
sort_descending: true # Will sort blogposts in archive list starting with newest one

# index menu
# Example:
menu:
  Blog: /archives
  Projects: /projects
  Resume: /resume
  Links: /links
  
stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .
  plugins: 'nib'