favicon: assets/favicon.ico
logo: assets/logo.png

# navbar
github_url: https://github.com/StrixSC/
mastodon_url: https://mastodon.social/explore
linkedin_url: https://linkedin.com
twitter_url: https://twitter.com/S7RIX


# index menu
# Example:
menu:
  Blog: /archives
  Projects: /projects
  Resume: /resume
  Links: /links
  